version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/longkey1/amazon-pa-api-proxy
    environment:
      GOPATH: "/go"
      GO111MODULE: "on"
    resource_class: small
    steps:
      - checkout
      - run: go get -u github.com/mitchellh/gox
      - run: gox --osarch "darwin/amd64 linux/amd64 windows/amd64" --output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}"
      - run: go build -o ./bin/amazon-pa-api-proxy
      - persist_to_workspace:
          root: .
          paths:
            - bin
            - dist

  release:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/longkey1/amazon-pa-api-proxy
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_USERNAME -r $CIRCLE_PROJECT_REPONAME v$(./bin/amazon-pa-api-proxy --version | cut -d " " -f 3) dist/

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
